config/routes.rb
Rails.application.routes.draw do
  
  root "sessions#new"

  resources :opinions, only: [:new, :index, :create, :show, :destroy]
  resources :followings, only: [:new, :create, :index,:destroy]
  resources :users , only: [:new, :index, :create,:show]
  resources :sessions, only: [:new, :index, :create,:destroy]
  resources :species, only: [:new, :index, :create]
  

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :statics, only: [:index]
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: 'User', foreign_key: 'followedid'
  belongs_to :user, class_name: 'User', foreign_key: 'followerid'
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  validates :opinion, presence: true, length: { maximum: 1000,
                                                too_long: '1000 characters in post is the maximum allowed.' }
  belongs_to :user, foreign_key: 'authorid'
end

app/models/species.rb
class Species < ApplicationRecord
  validates :specie, presence: true
  validates :content, presence: true
  validates :image, presence: true
  validates :location, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :fullname, presence: true
  validates :username, presence: true
  validates_uniqueness_of :username
  has_many :opinions, foreign_key: 'authorid', class_name: 'Opinion'
  has_many :followings
  has_many :followers, foreign_key: 'followerid', class_name: 'Following'
  has_many :follows, foreign_key: 'followedid', class_name: 'Following'
  has_many :species

  scope :not_follow, ->(user) { where.not(id: user.followers.map(&:followedid)) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def authorize
    redirect_to login_url, alert: 'Not authorized' if current_user.nil?
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  include ApplicationHelper
  def index
    @followings = current_user.followers
  end

  def create
    @following = current_user.followers.create!(following_params)

    redirect_back(fallback_location: root_path)
  end

  def destroy
    following = Following.find(params[:id])
    following.destroy

    redirect_back(fallback_location: root_path)
  end

  def following_params
    params.require(:following).permit(:followedid)
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :set_opinion, only: %i[show edit update destroy]
  before_action :authorize
  include ApplicationHelper
  # GET /opinions
  # GET /opinions.json
  def index
    @opinions = Opinion.all.order('created_at DESC').includes(:user)
    @opinion = current_user.opinions.build
    @not_followers = User.not_follow(current_user)
    @users = @not_followers.where.not(id: current_user.id).order('created_at DESC') unless current_user.nil?
  end

  # GET /opinions/1
  # GET /opinions/1.json
  def show; end

  # GET /opinions/new
  def new
    @opinion = current_user.opinions.build
  end

  # GET /opinions/1/edit
  def edit; end

  # POST /opinions
  # POST /opinions.json
  def create
    @opinion = current_user.opinions.build(opinion_params)

    if @opinion.save
      redirect_to opinions_path, notice: 'Opinion was successfully created.'

    else
      render :index

    end
  end

  # PATCH/PUT /opinions/1
  # PATCH/PUT /opinions/1.json
  def update
    if @opinion.update(opinion_params)
      redirect_to @opinion, notice: 'Opinion was successfully updated.'

    else
      render :edit

    end
  end

  # DELETE /opinions/1
  # DELETE /opinions/1.json
  def destroy
    @opinion.destroy

    redirect_to opinions_url, notice: 'Opinion was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_opinion
    @opinion = Opinion.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def opinion_params
    params.require(:opinion).permit(:opinion)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index; end

  def new
    @user = User.new
  end

  def create
    unless params[:username].present?
      flash[:alert] = 'Please provide username.'
      redirect_to new_session_path
      return
    end
    @user = User.find_by(username: params[:username])
    if @user
      session[:user_id] = @user.id
      redirect_to opinions_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Username is invalid'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path, notice: 'Logged out!'
  end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  before_action :set_species, only: %i[show edit update destroy]
  include ApplicationHelper
  # GET /species
  # GET /species.json
  def index
    @species = Species.all
    @not_followers = User.not_follow(current_user)
    @users = @not_followers.where.not(id: current_user.id).order('created_at DESC') unless current_user.nil?
  end

  def new
    @species = Species.all
    @not_followers = User.not_follow(current_user)
    @users = @not_followers.where.not(id: current_user.id).order('created_at DESC') unless current_user.nil?

    @specie = current_user.species.build
    @user = current_user
  end

  # GET /species/1
  # GET /species/1.json
  def show; end

  # GET /species/new

  # GET /species/1/edit
  def edit; end

  # POST /species
  # POST /species.json
  def create
    @species = current_user.species.build(species_params)

    redirect_to species_index_url, notice: 'Specie post created!' if @species.save
  end

  # PATCH/PUT /species/1
  # PATCH/PUT /species/1.json
  def update
    if @species.update(species_params)
      redirect_to species_path, notice: 'Specie was successfully updated.'

    else
      render :edit

    end
  end

  # DELETE /species/1
  # DELETE /species/1.json
  def destroy
    @species.destroy

    redirect_to species_url, notice: 'Specie was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_species
    @species = Specie.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def species_params
    params.require(:species).permit(:specie, :content, :image, :location, :date)
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  include ApplicationHelper
  def index
    @opinions = Opinion.all.order('created_at DESC')
    @opinion = current_user.opinions.build
    @not_followers = User.not_follow(current_user)
    @users = @not_followers.where.not(id: current_user.id).order('created_at DESC') unless current_user.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy]
  include ApplicationHelper
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @opinion = current_user.opinions.build
    @opinions = @user.opinions.order('created_at DESC')
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to opinions_path, notice: 'Thank you for signing up!'
    else
      render 'new'
    end
  end

  # Only allow a list of trusted parameters through.
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:fullname, :username, :photo, :coverimage, :opinions_count)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    return unless session[:user_id]

    @current_user ||= User.find_by_id(session[:user_id])
  end

  def error_flashes
    if flash[:notice]
      content_tag(:p, flash[:notice], class: 'alert alert-success')
    elsif flash[:alert]
      content_tag(:p, flash[:alert], class: 'alert alert-danger')
    end
  end
end

app/helpers/opinions_helper.rb
module OpinionsHelper
  def display_errors(post)
    return unless post.errors.full_messages.any?

    content_tag :p, "Post could not be saved. #{post.errors.full_messages.join('. ')}", class: 'errors'
  end

  def destroy_opinion(opinion, current_user)
    return unless opinion.authorid == current_user.id

    content_tag(:p, class: 'float-right') do
      link_to 'Destroy', opinion, method: :delete, data: { confirm: 'Are you sure?' }
    end
  end
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BiologistApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="notification is-primary global-notification text-light text-center m-0">      
      <%= error_flashes %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/opinions/_feed.html.erb
 
  <%= render 'opinions/form' , opinion: @opinion  %>


 

  <div class='box'> 
     <p class='n-posts'>NUMBER OF</p>
     <hr>
     <% @opinions.each do |opinion| %>
        <div class='row'>
          <a class='menu-ancho' href='users/<%= opinion.user.id %>'>
            <div class='square'>
              <img src="<%= opinion.user.photo %>" width='50'>
            </div>
          </a>
          <div class='box2'>
           <%= destroy_opinion(opinion,current_user) %>
            

            <a class='menu-ancho' href='users/<%= opinion.user.id %>'><p class='font-weight-bold'><%= opinion.user.username %></p></a>
            
            <p><%= opinion.opinion %></p>
            
          </div>
      </div> 
     <% end %>
  </div>
 

app/views/opinions/_form.html.erb
<div class='box border'>
  <%= form_for(@opinion) do |form| %>
    
    <%= form.label 'Share your opinion', class:'form-la' %>
    <%= form.text_area :opinion, class: 'form-control', placeholder: 'Write here' %>
    <%= display_errors(@opinion) %>
    <%= form.submit 'Save', class: 'btn btn-secondary buto' %>
  <% end %>
</div>

app/views/opinions/_menu.html.erb
<div class='colum'>
 <div class='img-header mx-auto row'>
  
  <div class='square'>
    <img src="<%= current_user.photo %>" width='50'>
  </div>
  <p class='name ml-3'><%= current_user.fullname.upcase %></p>
 </div>
 <div class='row follow'>
    <div class='text-center borders pt-3'>
        <p class='number'><%= current_user.followers.count %></p>
        <p class='fol'>Following</p>
    </div>
    
    <div class='text-center borders pt-3'>
        <p class='number'><%= current_user.follows.count %></p>
        <p class='fol'>Followers</p>
    </div>
 </div>
 <div>
 </div>
 <nav class='nav-menu'>
    <ul>
        <li><a href='/opinions' class='menu-anchor'><i class="fa fa-home" aria-hidden="true"></i> HOME</a></li>
        <li>@ CONNECT</li>
        <li><a href='/species' class='menu-anchor'># SPECIES SIGHTINGS</a></li>
        <li><a href="/users/<%= current_user.id %>" class='menu-anchor'><i class="fa fa-user" aria-hidden="true"></i> PROFILE</a></li>
        <li><a href='/statics' class='menu-anchor'><i class="fa fa-pie-chart" aria-hidden="true"></i> STATISTICS</a></li>
        <li><i class="fa fa-power-off menu-anchor" aria-hidden="true"><%= link_to ' LOGOUT', logout_path,
            data: { confimation: 'are you sure?' },
            class: 'menu-anchor'%></i>
        </li>
    </ul>
 </nav>
</div>

app/views/opinions/_who_follow.html.erb
<div class='whoftitle'>
  <div class='border-boto'>
    <p class='ml-5 mt-3'>WHO TO FOLLOW <i class="fa fa-superpowers " aria-hidden="true"></i></p>
    <hr>
    <% @users.each do |user| %>
      <div class='row'>
        <a href="/users/<%= user.id %>">
          <div class='circle my-3'>
            <img src="<%= user.photo %>" width='50'>
          </div>
        </a>  
        <a href="/users/<%= user.id %>">
          <div class='box3'>

            <p class='font-weight-bold'><%= user.fullname %></p>
       
          </div> 
        </a>   
        
          
          
      </div>

    <% end %>
    <a href='#' class='font-link-who'>Popular accounts - Find friends</a>
  </div>  
  <hr>
  <p class='ml-5 mt-3'>TRENDING <i class="fa fa-cog" aria-hidden="true"></i></p>
    <hr>
</div>

app/views/opinions/edit.html.erb
<h1>Editing Opinion</h1>

<%= render 'form', opinion: @opinion %>

<%= link_to 'Show', @opinion %> |
<%= link_to 'Back', opinions_path %>

app/views/opinions/index.html.erb
<div class='row index'>
  <div>
    <%= render 'menu' %>
  </div>
  
  <div class='marginLeft row'>
    <div class='wid'>
      <nav class="navbar navbar-expand-lg navl  navbar-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse justify-content-end mr-5" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active " href="#"><i class="fa fa-pencil linkNav" aria-hidden="true"></i></a>
            <a class="nav-link text-light" href="#"><i class="fa fa-envelope-o linkNav" aria-hidden="true"></i></a>
            <a class="nav-link text-light" href="#"><i class="fa fa-search linkNav" aria-hidden="true"></i></a>
            <a class="nav-link text-light" href="#"><i class="fa fa-cog  linkNav" aria-hidden="true"></i></a>
            
          </div>
        </div>
      </nav>
      <div class='row'>
        <div class='col-8 feed mx-auto'>
          <%= render 'feed' %>
        </div> 
        <div class='whof col-4'> 
          <%= render 'who_follow' %>
        </div>  
      </div>
    </div>
        
  </div>
  
</div>  

app/views/opinions/new.html.erb
<h1>New Opinion</h1>

<%= render 'form', opinion: @opinion %>

<%= link_to 'Back', opinions_path %>

app/views/opinions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Opinion:</strong>
  <%= @opinion.opinion %>
</p>

<%= link_to 'Edit', edit_opinion_path(@opinion) %> |
<%= link_to 'Back', opinions_path %>

app/views/species/_form.html.erb
  <%= bootstrap_form_for( @specie) do |form| %>
    <div class="pt-2 shadow pb-5  col-10 mb-5">
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
  
      <div class="field">
        
        <%= form.text_field :specie, placeholder:'specie name' %>
      </div>

      <div class="field">
      
        <%= form.text_area :content, placeholder:'Say something' %>
      </div>

      <div class="field">
        
        <%= form.text_field :image, placeholder:'Write the url of the images(http://www.imageexmaple.com)' %>
      </div>

      <div class="field">
        
        <%= form.text_field :location, placeholder:'Where this happen' %>
      </div>

      <div class="field">
      
        <%= form.date_field :date, placeholder:'date'%>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    </div>  

  <% end %>

app/views/species/edit.html.erb
<h1>Editing Species</h1>

<%= render 'form', species: @species %>

<%= link_to 'Show', @species %> |
<%= link_to 'Back', species_path %>

app/views/species/index.html.erb
<div class='row index'>
  <div>
    <%= render 'opinions/menu' %>
  </div>
  
  <div class='marginLeft row'>
    <div class='wid'>
      <nav class="navbar navbar-expand-lg navl  navbar-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse justify-content-end mr-5" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active " href="#"><i class="fa fa-pencil linkNav" aria-hidden="true"></i></a>
            <a class="nav-link text-light" href="#"><i class="fa fa-envelope-o linkNav" aria-hidden="true"></i></a>
            <a class="nav-link text-light" href="#"><i class="fa fa-search linkNav" aria-hidden="true"></i></a>
            <a class="nav-link text-light" href="#"><i class="fa fa-cog  linkNav" aria-hidden="true"></i></a>
            
          </div>
        </div>
      </nav>
      <div class='row  feed '>
        <div class='col-8 mx-auto text-center mt-3'>
          <a href='species/new' class='btn btn-primary mt-4"'>Share species sightings</a>
          <div class='row ml-2'>
            <% @species.each do |specie| %>
                <div class='box4'>
                  <p class='font-weight-bold text-left ml-2'><%= specie.specie.capitalize %></p>
                  <p class='font-weight-bold text-left username-grey ml-2'><%= specie.location.capitalize %></p>
                  <div class='square2'>
                    <img src="<%= specie.image %>" width='335' >
                  </div>
                  <p class='text-left  ml-2'><%= specie.date %></p>
                  <p class='text-left  ml-2'><%= specie.content %></p>
                  
                    
                </div>
            <% end %>  
          </div>
        </div> 
        <div class='whof col-4'> 
          <%= render 'opinions/who_follow' %>
        </div> 
      </div>
    </div>
        
  </div>
  
</div>  

app/views/species/new.html.erb
<div class='row index'>
  <div>
    <%= render 'opinions/menu' %>
  </div>
  
  <div class='marginLeft row'>
    <div class='wid'>
      <nav class="navbar navbar-expand-lg navl  navbar-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse justify-content-end mr-5" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active " href="#"><i class="fa fa-pencil linkNav" aria-hidden="true"></i></a>
            <a class="nav-link text-light" href="#"><i class="fa fa-envelope-o linkNav" aria-hidden="true"></i></a>
            <a class="nav-link text-light" href="#"><i class="fa fa-search linkNav" aria-hidden="true"></i></a>
            <a class="nav-link text-light" href="#"><i class="fa fa-cog  linkNav" aria-hidden="true"></i></a>
            
          </div>
        </div>
      </nav>
      <div class='col-12 feed mx-auto'>
        <div class='col-12 mx-auto'>        
          <%= render 'species/form', specie: @specie %>
        </div> 
      </div>
    </div>
        
  </div>
  
</div> 

app/views/species/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Specie:</strong>
  <%= @species.specie %>
</p>

<p>
  <strong>Content:</strong>
  <%= @species.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= @species.image %>
</p>

<p>
  <strong>Location:</strong>
  <%= @species.location %>
</p>

<p>
  <strong>Date:</strong>
  <%= @species.date %>
</p>

<%= link_to 'Edit', edit_species_path(@species) %> |
<%= link_to 'Back', species_path %>

app/views/statics/index.html.erb
<div class='row index'>
  <div>
    <%= render 'opinions/menu' %>
  </div>
  
  <div class='marginLeft row'>
    <div class='wid'>
      <nav class="navbar navbar-expand-lg navl  navbar-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse justify-content-end mr-5" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active " href="#"><i class="fa fa-pencil linkNav" aria-hidden="true"></i></a>
            <a class="nav-link text-light" href="#"><i class="fa fa-envelope-o linkNav" aria-hidden="true"></i></a>
            <a class="nav-link text-light" href="#"><i class="fa fa-search linkNav" aria-hidden="true"></i></a>
            <a class="nav-link text-light" href="#"><i class="fa fa-cog  linkNav" aria-hidden="true"></i></a>
            
          </div>
        </div>
      </nav>
      <div class='row'>
        <div class='col-8 feed mx-auto'>
          <div class='col-10 mx-auto box3'>
            <p class='font-weight-bold'>Opinions group by hour of day</p>
            <%= line_chart current_user.opinions.group_by_hour_of_day(:created_at).count %>
          </div>
          <div class='col-10 mx-auto box3'>
            <p class='font-weight-bold'>Opinions group by day of week</p>
            <%= column_chart current_user.opinions.group_by_day_of_week(:created_at, format: "%a").count %>
          </div>
        
        </div> 
        <div class='whof col-4'> 
          <%= render 'opinions/who_follow' %>
        </div>  
      </div>
    </div>
        
  </div>
  
</div>

app/views/users/_form.html.erb
<%= bootstrap_form_for( @user) do |form| %>
  <div class="pt-2 shadow pb-5 mt-5 container col-lg-4 col-md-5 mb-5">
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
     
      <%= form.text_field :fullname %>
    </div>

    <div class="field">
     
      <%= form.text_field :username %>
    </div>

    <div class="field">
      
      <%= form.text_field :photo %>
    </div>

    <div class="field">
      
      <%= form.text_field :coverimage %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>  
<% end %>

app/views/users/_user_info.html.erb
<div class=''>
  <div class='circle2 mt-2'>
    <img src="<%= @user.photo %>" width='130'>
  </div>
  

  <p class='font-weight-bold titlename mt-2'><%= @user.fullname.upcase %></p>
  <p class='font-weight-bold text-center username-grey'>@<%= @user.username %></p>
  
  <div class='text-center'>
    <% if current_user.followers.find_by(followedid:@user.id) || current_user.id == @user.id %>
      
    <% else %>
      <%= form_for current_user.followers.build(follower: @user) do |f| %>
        <%= f.hidden_field :followedid %>
        <%= f.hidden_field :followerid %>
        <%= f.submit 'Follow', class:'follow-boton mb-4' %>
      <% end %>  
    <% end %>    
  </div>  

  <table>
    
    <tr>
      <th><p class='titlename mt-1 lineh'><%= @user.opinions.count %></p><p class='text-center username-grey'>Opinions</p></th>
      <th><p class='titlename mt-1 lineh'><%= @user.followers.count %></p><p class='text-center username-grey'>Following</p></th>
      <th><p class='titlename mt-1 lineh'><%= @user.follows.count %></p><p class='text-center username-grey'>Followers</p></th>
    </tr>

  </table>
  
  <p class='text-left ml-4 mt-3 writee'>FOLLOWED BY</p>
  <hr>
  <% @user.follows.includes(:user).each do |follower| %>
    <a href='/users/<%= follower.id %>'>
      <div class='row'>
      
        <div class='circle my-3'>
          <img src="<%= follower.user.photo %>" width='50'>
        </div>
          
        <div class='box3'>

          <p class='font-weight-bold'><%= follower.user.fullname %></p>
        
        </div>  
        
          
          
      </div>
    </a>  

  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

app/views/users/new.html.erb
<h1 class='text-center'>Sign up</h1>
<%= bootstrap_form_for( @user) do |form| %>
  <div class="pt-2 shadow pb-5 mt-5 container col-lg-4 col-md-5 mb-5">
    <% if @user.errors.any? %>
      <div id="error_explanation">
        

      <ul>
        <%@user.errors.full_messages.each do |error| %>
        <li><%= error%></li>
        <%end%>
      </ul>
      </div>
    <% end %>

    <div class="field">
     
      <%= form.text_field :fullname, placeholder:'fullname here' %>
    </div>

    <div class="field">
     
      <%= form.text_field :username, placeholder:'user name here' %>
    </div>

    <div class="field">
      
      <%= form.text_field :photo, placeholder:'http://www.imageexmaple.com (size 100x100)' %>
    </div>

    <div class="field">
      
      <%= form.text_field :coverimage, placeholder:'http://www.imageexmaple.com (size 900x350)' %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>  
<% end %>


<div class='text-center'>
  <%= link_to 'Sign in', login_path, class: 'nav-link text-primary' %>
</div>

app/views/users/show.html.erb
<div class='row index'>
  <div>
    <%= render 'opinions/menu' %>
  </div>
  
  <div class='marginLeft row'>
    <div class='wid'>
      <nav class="navbar navbar-expand-lg navl  navbar-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse justify-content-end mr-5" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active " href="#"><i class="fa fa-pencil linkNav" aria-hidden="true"></i></a>
            <a class="nav-link text-light" href="#"><i class="fa fa-envelope-o linkNav" aria-hidden="true"></i></a>
            <a class="nav-link text-light" href="#"><i class="fa fa-search linkNav" aria-hidden="true"></i></a>
            <a class="nav-link text-light" href="#"><i class="fa fa-cog  linkNav" aria-hidden="true"></i></a>
            
          </div>
        </div>
      </nav>
      
      <div class='row col-12'>
        <div class='col-8 feed mx-auto'>
          <div class='coverimg'>
            <img src="<%= @user.coverimage %>">
          </div>
          
          <%= render 'opinions/feed' %>
        </div>
        <div class='col-4 whof'> 
          <%= render 'user_info' %>        
        </div>  
       
      </div>
    </div>
    
   
   

   

    

     
        
     
    


    
  </div>
  
</div>  